services:
  mariadb:
    image: mariadb:12.1
    platform: linux/arm64/v8
    container_name: meet_talent_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "meet-talent"
      MARIADB_USER: "meet-talent-api"
      MARIADB_PASSWORD: "meet-talent-secret-key"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: meet_talent_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "meettalent"
      MINIO_ROOT_PASSWORD: "meettalent-secret-key"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  mariadb_data:
  minio_data: