services:
  mariadb:
    image: mariadb:12.1
    platform: linux/arm64/v8
    container_name: meet_talent_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "meet-talent"
      MARIADB_USER: "meet-talent-api"
      MARIADB_PASSWORD: "meet-talent-secret-key"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: