# Spring Configuration
spring.application.name=backend
spring.profiles.active=dev
server.servlet.context-path=/api

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.zpcafhjuotmpncrzihkq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=carte0-tyzzig-mobnuM

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Supabase
supabase.jwt.secret=RafkaB9wS7Y0nT6QJDngVFZ2dtl7xz1tD/w5MtWFNRx083Xf1MOqRtZJzZWHRyaKeNwHzidnL+waN6IZjZCzjA==
supabase.jwt.url=https://zpcafhjuotmpncrzihkq.supabase.co/auth/v1/.well-known/jwks.json

# DEBUG
logging.level.org.springframework.security=DEBUG